name: Build example


on:
  push:
    branches: 
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    branches: [ '**' ]

jobs:
  build-example:
    runs-on: ubuntu-latest
    steps:
      - name: Setup typst  
        uses: yusancky/setup-typst@v2
        id: setup-typst
        with:
          version: 'latest'
      - name: Setup Just
        uses: extractions/setup-just@v2
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: typst version
        run: typst --version
      - name: Compile
        run: just build-examples
      - name: Upload example PDF 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}_PDF_EXAMPLES
          path: examples/*
          if-no-files-found: error