name: Comment Artifact URL on PR

on:
  workflow_run:
    # types:
      # - "completed"
    workflows:
      - "Build example"

jobs:
  comment-on-pr:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment: basic_env
    permissions:
      pull-requests: write
    steps:
      - name: Get Artifact URL & PR Info
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          WORKFLOW_RUN_EVENT_OBJ: ${{ toJSON(github.event.workflow_run) }}
        run: |

          PREVIOUS_JOB_ID=$(jq -r '.id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
          echo "Previous Job ID: $PREVIOUS_JOB_ID"
          echo "PREVIOUS_JOB_ID=$PREVIOUS_JOB_ID" >> "$GITHUB_ENV"

          ARTIFACT_URL=$(gh api "/repos/$OWNER/$REPO/actions/artifacts" \
            --jq ".artifacts.[] |
            select(.workflow_run.id==${PREVIOUS_JOB_ID}) |
            select(.expired==false) |
            .archive_download_url")

          echo "ARTIFACT URL: $ARTIFACT_URL"
          echo "ARTIFACT_URL=$ARTIFACT_URL" >> "$GITHUB_ENV"

          PR_NUMBER=$(jq -r '.pull_requests[0].number' \
            <<< "$WORKFLOW_RUN_EVENT_OBJ")

          echo "PR Number: $PR_NUMBER"
          echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_ENV"

          HEAD_SHA=$(jq -r '.pull_requests[0].head.sha' \
            <<< "$WORKFLOW_RUN_EVENT_OBJ")

          echo "Head sha: $HEAD_SHA"
          echo "HEAD_SHA=$HEAD_SHA" >> "$GITHUB_ENV"

      - name: Update Comment
        env:
          JOB_PATH: "${{ github.server_url }}/${{ github.repository }}/actions/\
            runs/${{ env.PREVIOUS_JOB_ID }}"
          HEAD_SHA: ${{ env.HEAD_SHA }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          edit-mode: replace
          issue-number: ${{ env.PR_NUMBER }}
          token: ${{ secrets.TOKEN }}
          body: |
            ## Build Preview

            You can find files attached to the below linked Workflow Run URL (Logs).

            Please note that files only stay for around 90 days!

            | Name      | Link |
            --------------------------------------------------------------------
            | Commit    | ${{ env.HEAD_SHA }} |
            | Workflow Run (click here to get PDF link)      | ${{ env.JOB_PATH }} |

            [badge]: https://img.shields.io/badge/Build-Success!-3fb950?logo=github&style=for-the-badge
